### ISSUE TITLE
.topsの表示非表示について～

### ISSUE THREAD

**Issue by tamagoooooo** [seikosf24/seikosf24.github.io#3]
これBE SEIKOの文字とバナーだけtranslateつけてるけど右の文字(スマホならメニュー)にもつけなくていいの?

右の文字だけ残ったままだとみにくいわ

**Comment by seikosf24** [comment]
そこ、自分がつけた時になんかバグったからつけてなかっただけで
出来そうならぜひやってほしい

**Comment by tamagoooooo** [comment]
一応なおした。要チェック

**Comment by seikosf24** [comment]
良き…なんだけど、それをスマホで見るとメニュー開いて上下させた時にリストが動くんよね。
些細な問題やから無視でもいいんやけど。

**Comment by tamagoooooo** [comment]
なおした
>スマホで見るとメニュー開いて上下させた時にリストが動くんよね。
